# envs - [bin_pack, cleaner, connector, cvrp, flat_pack, game_2048, graph_coloring, 
# job_shop, knapsack, maze, minesweeper, mmst, multi_cvrp, pac_man, robot_warehouse, 
# lbf, rubiks_cube, search_and_rescue, sliding_tile_puzzle, snake, sokoban, sudoku, tetris, tsp]
# + New one, tarware (Task assignment Rware)
defaults:
    - _self_
    - env: tarware 

agent: a2c  # [random, a2c]

seed: 0

logger:
    type: tensorboard  # [neptune, tensorboard, terminal]
    save_checkpoint: true  # [false, true]
    name: ${agent}_${env.name}
